#!/bin/bash
# Run study 2's simulation locally in the project's Docker container.
# Usage: ./3_study2_0_run_in_command_line

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export RUN_REP="200"                                                            # 200 reps = 12 hours
export SEED_ENV="10"

docker run --rm \
  -v /home/giaco:/home/giaco \
  -w /home/giaco/GitHub/8_bayes_reliability \
  -e OMP_NUM_THREADS \
  -e OPENBLAS_NUM_THREADS \
  -e MKL_NUM_THREADS \
  -e VECLIB_MAXIMUM_THREADS \
  -e RUN_REP \
  -e SEED_ENV \
  bignardig/tidyverse461:v2 Rscript 3_study2_1_simulate.R
