#!/bin/bash
# Run study 3's simulation locally in the project's Docker container.
# Usage: ./4_study3_0_run_in_command_line

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1
export RUN_REP="12"                                                      # 5 reps = 6.2 hours (20 takes 1.02 days)
export SEED_ENV="6"

docker run --rm \
  -v /home/giaco:/home/giaco \
  -w /home/giaco/GitHub/8_bayes_reliability \
  -e OMP_NUM_THREADS \
  -e OPENBLAS_NUM_THREADS \
  -e MKL_NUM_THREADS \
  -e VECLIB_MAXIMUM_THREADS \
  -e RUN_REP \
  -e SEED_ENV \
  bignardig/tidyverse461:v3 Rscript 4_study3_1_simulate.R
